[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[envs]
PYTHON_VERSION = "3.10.12"
NIXPACKS_PYTHON_VERSION = "3.10.12" 